import {
  chmodSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { intentsSnippet, type ScaffoldOptions } from "./options.js";
import { renderTemplate, type TemplateVars } from "./render.js";
import { TEMPLATE_VERSIONS } from "./versions.js";

/**
 * Template source files use filesystem-safe names for content that must
 * render as a dotfile — bundlers and some editors mishandle a source tree
 * that already contains `.gitignore`/`.env.example`. Renamed only at write
 * time, after templating.
 */
export const RENAME: Record<string, string> = {
  _gitignore: ".gitignore",
  "env.example": ".env.example",
};

export interface ScaffoldFile {
  readonly path: string;
  readonly content: string;
  readonly mode?: number;
}

export function templatesDir(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), "..", "templates");
}

export function templateVars(options: ScaffoldOptions): TemplateVars {
  return {
    projectName: options.projectName,
    nodeMajor: "22",
    vCore: TEMPLATE_VERSIONS.alenexumCore,
    vDiscord: TEMPLATE_VERSIONS.alenexumDiscord,
    vTelemetry: TEMPLATE_VERSIONS.alenexumTelemetry,
    vJobs: TEMPLATE_VERSIONS.alenexumJobs,
    vTesting: TEMPLATE_VERSIONS.alenexumTesting,
    vDiscordJs: TEMPLATE_VERSIONS.discordJs,
    vDotenv: TEMPLATE_VERSIONS.dotenv,
    vTsx: TEMPLATE_VERSIONS.tsx,
    vTsup: TEMPLATE_VERSIONS.tsup,
    vTypescript: TEMPLATE_VERSIONS.typescript,
    vVitest: TEMPLATE_VERSIONS.vitest,
    vBiome: TEMPLATE_VERSIONS.biome,
    vNodeTypes: TEMPLATE_VERSIONS.nodeTypes,
    intents: intentsSnippet(options.intents),
    telemetry: options.features.telemetry,
    jobs: options.features.jobs,
    testing: options.features.testing,
    standardIntents: options.intents === "standard",
  };
}

interface SourceFile {
  readonly rel: string;
  readonly root: string;
}

function collectFiles(dir: string, root: string, out: SourceFile[]): void {
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === ".DS_Store") continue;
    const absolute = join(dir, entry.name);
    if (entry.isDirectory()) {
      collectFiles(absolute, root, out);
    } else {
      out.push({ rel: relative(root, absolute).replace(/\\/g, "/"), root });
    }
  }
}

export function planScaffold(
  options: ScaffoldOptions,
  fromDir: string = templatesDir(),
): ScaffoldFile[] {
  const vars = templateVars(options);
  const sources: SourceFile[] = [];

  const baseDir = join(fromDir, "base");
  collectFiles(baseDir, baseDir, sources);
  if (options.features.jobs) {
    const jobsDir = join(fromDir, "features", "jobs");
    collectFiles(jobsDir, jobsDir, sources);
  }
  if (options.features.testing) {
    const testingDir = join(fromDir, "features", "testing");
    collectFiles(testingDir, testingDir, sources);
  }

  const files: ScaffoldFile[] = sources.map(({ rel, root }) => {
    const segments = rel.split("/");
    const fileName = segments[segments.length - 1] as string;
    const renamed = RENAME[fileName] ?? fileName;
    const target = [...segments.slice(0, -1), renamed].join("/");
    const source = readFileSync(join(root, rel), "utf8");
    return { path: target, content: renderTemplate(source, vars) };
  });

  if (options.token !== undefined || options.guildId !== undefined) {
    files.push({ path: ".env", content: envFile(options), mode: 0o600 });
  }

  return files.sort((a, b) => (a.path < b.path ? -1 : 1));
}

function envFile(options: ScaffoldOptions): string {
  const lines = [
    "# Generated by create-alenexum-bot — never commit real tokens.",
    `DISCORD_TOKEN=${options.token ?? ""}`,
    `GUILD_ID=${options.guildId ?? ""}`,
    `DEPLOY_MODE=${options.deployMode}`,
    `LOG_LEVEL=${options.logLevel}`,
  ];
  return `${lines.join("\n")}\n`;
}

export function isNonEmptyDir(path: string): boolean {
  try {
    return readdirSync(path).length > 0;
  } catch {
    return false;
  }
}

export function writeScaffold(
  targetDir: string,
  files: readonly ScaffoldFile[],
  options: { readonly force: boolean },
): void {
  if (isNonEmptyDir(targetDir) && !options.force) {
    throw new Error(
      `Target directory ${targetDir} is not empty. Re-run with --force to overwrite.`,
    );
  }
  mkdirSync(targetDir, { recursive: true });
  for (const file of files) {
    const absolute = resolve(targetDir, file.path);
    mkdirSync(dirname(absolute), { recursive: true });
    writeFileSync(absolute, file.content, { mode: file.mode ?? 0o644 });
    if (file.mode !== undefined) {
      chmodSync(absolute, file.mode);
    }
  }
}

export function installArgs(packageManager: string): readonly string[] {
  return [packageManager, "install"];
}
